from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from io import BytesIO

def generate_invoice_pdf(transaction, user, events):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    ink = colors.HexColor("#0F172A")
    teal = colors.HexColor("#0F6B62")
    gold = colors.HexColor("#C98A2C")
    slate = colors.HexColor("#64748B")

    # Header
    c.setFillColor(ink)
    c.rect(0, height - 30*mm, width, 30*mm, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(20*mm, height - 18*mm, "TrustLedger")
    c.setFont("Helvetica", 10)
    c.drawString(20*mm, height - 25*mm, "Transaction Invoice")

    c.setFillColor(gold)
    c.setFont("Helvetica-Bold", 12)
    c.drawRightString(width - 20*mm, height - 18*mm, f"No. {transaction.id:06d}")

    # Business / Customer info
    y = height - 45*mm
    c.setFillColor(ink)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20*mm, y, "From")
    c.setFont("Helvetica", 10)
    c.drawString(20*mm, y - 6*mm, user.business_name)
    c.drawString(20*mm, y - 11*mm, user.email)

    c.setFont("Helvetica-Bold", 11)
    c.drawString(110*mm, y, "To")
    c.setFont("Helvetica", 10)
    c.drawString(110*mm, y - 6*mm, transaction.customer_contact)

    # Line
    y -= 22*mm
    c.setStrokeColor(colors.HexColor("#E2DED4"))
    c.line(20*mm, y, width - 20*mm, y)

    # Item table header
    y -= 10*mm
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(slate)
    c.drawString(20*mm, y, "DESCRIPTION")
    c.drawRightString(width - 20*mm, y, "AMOUNT")

    y -= 7*mm
    c.setStrokeColor(colors.HexColor("#E2DED4"))
    c.line(20*mm, y, width - 20*mm, y)

    y -= 8*mm
    c.setFont("Helvetica", 10)
    c.setFillColor(ink)
    c.drawString(20*mm, y, transaction.item_description)
    c.drawRightString(width - 20*mm, y, f"NGN {transaction.amount:,.2f}")

    y -= 6*mm
    c.line(20*mm, y, width - 20*mm, y)

    y -= 10*mm
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(teal)
    c.drawRightString(width - 20*mm, y, f"Total: NGN {transaction.amount:,.2f}")

    # Status
    y -= 15*mm
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(slate)
    c.drawString(20*mm, y, "STATUS")
    y -= 6*mm
    c.setFont("Helvetica", 10)
    c.setFillColor(ink)
    c.drawString(20*mm, y, f"Payment: {transaction.payment_status}   |   Delivery: {transaction.delivery_status}   |   Overall: {transaction.overall_status}")

    # History
    y -= 15*mm
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(slate)
    c.drawString(20*mm, y, "HISTORY")
    y -= 7*mm
    c.setFont("Helvetica", 9)
    c.setFillColor(ink)
    for e in events:
        timestamp = e.created_at.strftime("%b %d, %Y %I:%M %p")
        line = f"{timestamp} — {e.event_type.replace('_', ' ').title()}"
        c.drawString(20*mm, y, line)
        y -= 5.5*mm
        if y < 30*mm:
            c.showPage()
            y = height - 30*mm

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(slate)
    c.drawString(20*mm, 15*mm, "Generated by TrustLedger — trusted transaction tracking.")

    c.save()
    buffer.seek(0)
    return buffer
